### ISSUE TITLE
[BUG] Cannot remove contact tag

### ISSUE THREAD

**Issue by rquarta-extera** [leadbi/leadbi-php-sdk#11]
Hi @andrei-tofan 

I need to remove tags from contacts but the [API endpoints](https://github.com/leadbi/leadbi-php-sdk/blob/3182151810d0f4e68258e5b3b6cdea7941fdb942/lib/LeadBI/Resources/Tags.php#L51-L64) don't work. It could be useful to remove a tag by name or ID.

Could you check this?

Thanks
Riccardo

**Comment by leadbi** [comment]
Hi Riccardo,

We've fixed the api call.

Kind regards,
Andrei
