### ISSUE TITLE
[HOWTO] Placeholder support in HTML

### ISSUE THREAD

**Issue by lucamussoni** [leadbi/leadbi-php-sdk#13]
Hi @andrei-tofan 

I would like to ask you if it's possible to set placeholders in the html, in order to customize the output per single user (for example $NAME or $EMAIL).

I need to add an "unsubscribe" button, and the url must contains the email address of the specific user.

Thank you and best regards

Luca
Extera Digital Agency

**Comment by leadbi** [comment]
Hi Luca,

This are the placeholders for the you can use in the body and subject of the email.
https://gist.github.com/leadbi/bb91461cc63814028a9834cb90713e1b

Kind regards,
Andrei
