### ISSUE TITLE
[BUG] Cannot create newsletters

### ISSUE THREAD

**Issue by rquarta-extera** [leadbi/leadbi-php-sdk#2]
Hi @leadbi ,
I'm not able to create newsletters using the SDK. Every time I call the function **create** on **Newsletters** class, it gives me this message as answer: **Something went wrong**. I tried with some params (_name_, _subject_, _template_, ecc) but the answer is always the same.

Could you review this issue? Or maybe tell me how to build the body of the request.

Thanks,
Riccardo

**Comment by leadbi** [comment]
I will add a example, in the next few days

**Comment by leadbi** [comment]
We've added a newsletter example to the repo:
https://github.com/leadbi/leadbi-php-sdk/blob/master/examples/newsletter_example1.php
