### ISSUE TITLE
[BUG] Wrong string concatenator

### ISSUE THREAD

**Issue by rquarta-extera** [leadbi/leadbi-php-sdk#3]
Hi @leadbi 
There are wrong string concatenators (+ instead of .) in many classes:

- https://github.com/leadbi/leadbi-php-sdk/blob/ab7c1c3a08bbdb53a2d7db4961d6708a9b4ac171/lib/LeadBI/Resources/Newsletters.php#L26
- https://github.com/leadbi/leadbi-php-sdk/blob/ab7c1c3a08bbdb53a2d7db4961d6708a9b4ac171/lib/LeadBI/Resources/Newsletters.php#L39
and so on...

I correct them with this PR #1 , could you merge it please?

Thanks,
Riccardo

**Comment by leadbi** [comment]
Thx
