### ISSUE TITLE
[BUG] Wrong variable wrapping

### ISSUE THREAD

**Issue by rquarta-extera** [leadbi/leadbi-php-sdk#5]
Hi @leadbi 
There are several bugs inside class [Tags](https://github.com/leadbi/leadbi-php-sdk/blob/master/lib/LeadBI/Resources/Tags.php) about wrong variable wrapping:

- https://github.com/leadbi/leadbi-php-sdk/blob/ab7c1c3a08bbdb53a2d7db4961d6708a9b4ac171/lib/LeadBI/Resources/Tags.php#L23

- https://github.com/leadbi/leadbi-php-sdk/blob/ab7c1c3a08bbdb53a2d7db4961d6708a9b4ac171/lib/LeadBI/Resources/Tags.php#L39

- https://github.com/leadbi/leadbi-php-sdk/blob/ab7c1c3a08bbdb53a2d7db4961d6708a9b4ac171/lib/LeadBI/Resources/Tags.php#L55

- https://github.com/leadbi/leadbi-php-sdk/blob/ab7c1c3a08bbdb53a2d7db4961d6708a9b4ac171/lib/LeadBI/Resources/Tags.php#L62

I fix this issue in my PR #1, could you merge it please?

Thanks,
Riccardo

**Comment by leadbi** [comment]
Thx for the fix
