### ISSUE TITLE
[BUG] Cannot assign tag to contact

### ISSUE THREAD

**Issue by rquarta-extera** [leadbi/leadbi-php-sdk#6]
Hi @leadbi 
I'm not able to assign a tag to a contact with _tag_name_ attribute. Every time I call the function **assignTagToContact** on **Tags** class, it gives me this message as answer: **Something went wrong**.

Could you fix this issue?

Thanks,
Riccardo

**Comment by leadbi** [comment]
We will checkout the issue and get back to you

**Comment by leadbi** [comment]
We've added an example and fixed the issue, tag assignment was disabled for api users.
