### ISSUE TITLE
[BUG] Wrong API endpoint

### ISSUE THREAD

**Issue by rquarta-extera** [leadbi/leadbi-php-sdk#7]
Hi @leadbi 
I have found a wrong API endpoint inside Tags class: https://github.com/leadbi/leadbi-php-sdk/blob/ab7c1c3a08bbdb53a2d7db4961d6708a9b4ac171/lib/LeadBI/Resources/Tags.php#L48

The function is **getContactTags** but the endpoint is about prospects.

I fix it with the PR #1 , could you merge it please?

Thanks,
Riccardo

**Comment by leadbi** [comment]
PR Merged
Thx
