### ISSUE TITLE
[BUG] Query contacts

### ISSUE THREAD

**Issue by rquarta-extera** [leadbi/leadbi-php-sdk#8]
Hi @leadbi 
I see inside the SDK that it's possible to [filter contacts by tags](https://github.com/leadbi/leadbi-php-sdk/blob/42c6478e4687537d05dfceb4257756bbe812d7ae/lib/LeadBI/Resources/ProspectContacts.php#L24) but when I use this filter I receive a **Something went wrong** as answer.

Here is a portion of code:
```
...
$api = new ProspectContacts($config);
$contacts = $api->query($website_id, [
    'tags' => ['tag1', 'tag2']
]);
```

Can you check this?

Thanks,
Riccardo

**Comment by andrei-tofan** [comment]
Hi Riccardo, we are checking the issue, will get back with an answer asap.

**Comment by andrei-tofan** [comment]
Hi Riccardo, we added a fix for the tags filter and an example of filters for tags
