### ISSUE TITLE
[HOWTO] Create newsletter with tags filters

### ISSUE THREAD

**Issue by rquarta-extera** [leadbi/leadbi-php-sdk#9]
Hi @leadbi 
I see that it's possible to set filters on the creation of a newsletter via API. Is it possible to set tags filter and preselect users with matched tags? If so, how can I do that?

Thanks,
Riccardo

**Comment by leadbi** [comment]
Hi Riccardo,

The filters filed is used only to store filters for the ui. The campaign will be sent only to the contacts from the contacts array or new contacts from the list.

Kind regards,
Andrei
